<a href="https://colab.research.google.com/github/EslamWalid/Deep_learning_ITI/blob/main/Neural_Netowrk_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# appling Code from "Nueral Network from scratch in python" Book

In [1]:
!sudo apt-get install python3.7.7
! pip install numpy==1.18.2
! pip install matplotlib==3.2.1

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package python3.7.7
E: Couldn't find any package by glob 'python3.7.7'
E: Couldn't find any package by regex 'python3.7.7'
  Using cached numpy-1.18.2.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


### first neural network

In [2]:
import numpy as np
import matplotlib

In [3]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3

outputs=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(outputs)


35.7


### appling weights as Book

In [4]:
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

outputs=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(outputs)


2.3


In [5]:
# adding one more input
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

outputs=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(outputs)


4.8


In [7]:
# using 3 neurons

inputs1=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]
bias1=2
bias2=3
bias3=0.5

outputs=[inputs1[0]*weights1[0]+inputs1[1]*weights1[1]+inputs1[2]*weights1[2]+inputs1[3]*weights1[3]+bias1,
         inputs1[0]*weights2[0]+inputs1[1]*weights2[1]+inputs1[2]*weights2[2]+inputs1[3]*weights2[3]+bias2,
         inputs1[0]*weights3[0]+inputs1[1]*weights3[1]+inputs1[2]*weights3[2]+inputs1[3]*weights[3]+bias3]
print(outputs)




[4.8, 1.21, 2.71]


### Dot product

In [13]:

inputs1=[1,2,3,2.5]
weight=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]

layer_outputs =[]

for neuron_weights ,neuron_bias in zip(weight,bias):
  neuron_output=0

  for n_input,weight in zip(inputs,neuron_weights):
    neuron_output+= n_input*weight

  neuron_output+=neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)


[4.8, 1.21, 2.385]


In [14]:
inputs=[1,2,3,2.5]
weight=[0.2,0.8,-0.5,1.0]
bias=2

output=np.dot(inputs,weight)+bias
print(output)


4.8


In [18]:

inputs=[1,2,3,2.5]
weight=[[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]

output1=np.dot(weight,inputs)+bias

print(output1)


[4.8   1.21  2.385]


### Batches, Layers, and Objects

In [20]:

inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
weight=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]

output1=np.dot(inputs,np.array(weight).T)+bias

print(output1)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [22]:
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
weight=[[0.2,0.8,-0.5,1.0],
        [0.5,-0.91,0.26,-0.5],
        [-0.26,-0.27,0.17,0.87]]
bias=[2,3,0.5]
# second layer
weight2=[[0.1,-0.14,0.5],
        [-0.5,0.12,-0.33],
        [-0.44,0.73,-0.13]]
bias2=[-1,2,-0.5]

layer1=np.dot(inputs,np.array(weight).T)+bias
layer2_output=np.dot(layer1,np.array(weight2).T)+bias2

print(layer2_output)


[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [29]:
np.random.seed(0)
class Layer_Dense:
  def __init__(self, n_inputs , n_neurons):
    self.weights= 0.10 * np.random.randn(n_inputs,n_neurons)
    self.biases= np.zeros((1,n_neurons))

  def forward(self, inputs):
    self.outputs=np.dot(inputs,self.weights)+self.biases

In [31]:
X=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

Layer1=Layer_Dense(4, 5)

Layer2=Layer_Dense(5,2)

Layer1.forward(X)
Layer2.forward(Layer1.outputs)
print(Layer2.outputs)


[[ 0.07600385  0.04015067]
 [-0.03707247 -0.0575363 ]
 [ 0.04924432  0.02825296]]
